import type { Metadata } from "next";
import "./globals.scss";
import MenuContext from "@/utils/MenuContext";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <MenuContext>
            <Header />
            {children}
            <Footer />
          </MenuContext>
        </body>
      </html>
    </ClerkProvider>
  );
}
